version: '3'
services:
    yc:
        image: 'cr.yandex/yc/yandex-docker-local-ydb:latest'
        container_name: ydb-local
        hostname: localhost
        ports:
            - 2135:2135
            - 8765:8765
            - 2136:2136
        volumes:
            - ./ydb_certs:/ydb_certs
            - ./ydb_data:/ydb_data
        environment:
            - YDB_DEFAULT_LOG_LEVEL=NOTICE
            - GRPC_TLS_PORT=2135
            - GRPC_PORT=2136
            - MON_PORT=8765
